config/routes.rb
Rails.application.routes.draw do
  resources :inventories do
    collection do
      get  :import, action: 'bulk'
      post :import, action: 'bulk_import'
      get  'report/:store/:code', action: 'report', as: 'report'
      delete 'clear'
    end
  end

  root 'inventories#index'

end

app/models/inventory.rb
class InventoryStatus
  attr_accessor :valid, :invalid, :total
  attr_reader :errors

  def initialize
    @total = @valid = @invalid = 0
    @errors = Array.new
  end

  def <<(input)
    @errors << input
  end
end

class Inventory < ActiveRecord::Base
  attr_accessor :product, :bulk
  # before_save :split_product
  before_save :flag_update

  validates_presence_of :store, :code, :width, :feet
  validates :roll, presence: true, uniqueness: { :scope => :code }

  def self.bulk_import(data)
    line_count = 0
    status = InventoryStatus.new
    record = nil

    data.split("\r\n").each do |line|
      if !line.blank? and ( line[0].ord == 34 or line[0].ord == 64 or line == 'zy' ) # Beginning of record or end of data
        # Start the record
        if line[0].ord == 34
          line_count = 0
          status.total += 1
        else
          line_count = -1
        end

        # Save the record and record any errors
        if record
          if record.valid?
            record.save
            status.valid += 1
          else
            status.invalid += 1
            if record.kind_of?(Inventory)
              status << record.errors.map(&:full_messages)
            else
              status << 'Invalid data received in input'
            end
          end
        end
      end

      case line_count
        when -1 then break
        when 0 then record = new_by_product(line)
        when 1 then record.width  = line.to_i
        when 2 then record.feet   = line.to_i
        when 3 then record.inches = line.to_i || 0
        when 4 then record.store  = line.to_i || 0
        else
          status.errors << 'Record overflow occurred, too many record lines or we did not find a delimiter.'
          break
      end
      line_count += 1
    end

    status << 'We did not find the end of the data record, the last entry may not have been saved' if line_count > 0
    status << 'No valid record(s) were found in input' if status.total > 0 and status.valid == 0
    status << 'No record(s) found in input' if status.total == 0
    status
  end

  def length_to_f
    feet.to_f + (inches.to_f/12).round(2)
  end

  def length
    (length_to_f % 1).zero? ? length_to_f.to_i : length_to_f
  end

  def sq_feet
    (length * width).round(2)
  end

  def yards
    (length * 0.33).round(2)
  end

  def sq_yards
    (yards * width).round(2)
  end

  def product_code
    '%02d' % code
  end

  def inventory_code(pre = nil)
    "#{pre}#{product_code}#{roll}"
  end

  def self.new_by_product(product)
    find_or_create_by split_product(product) if product
  end

  private

  def flag_update
    self.updated = true
  end

  def self.split_product(product)
    if product and product.match(/.(\d{2})(.+)/)
      { code: $1.to_i, roll: $2.to_s }
    else
      { code: nil, roll: nil }
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate

  protected

  def authenticate
    return true if session[:access]

    authenticate_or_request_with_http_basic do |name, pass|
      if name == ENV['USER_NAME'] && pass == ENV['USER_PASS']
        session[:access] = 'user'
        flash[:notice] = 'Successfully Logged in'
        return true
      end

      if name == ENV['ADMIN_NAME'] && pass == ENV['ADMIN_PASS']
        session[:access] = 'admin'
        flash[:notice] = 'Successfully Logged in as Admin'
        return true
      end

      false
    end
  end
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :set_inventory, only: [:show, :edit, :update, :destroy]

  # GET /inventories
  # GET /inventories.json
  def index
    search_params = params[:inventory] || {}

    @checked_stores = []
    @checked_codes  = []

    @stores      = Inventory.all.collect(&:store).uniq.sort
    @products    = Inventory.all.collect(&:code).uniq.sort

    if search_params and search_params.any?
      @checked_stores = search_params[:store] if search_params.has_key?(:store)
      @checked_codes  = search_params[:code]  if search_params.has_key?(:code)
    else
      if session[:filter]
        @checked_stores = search_params[:store] = session[:filter]['stores']
        @checked_codes  = search_params[:code]  = session[:filter]['codes']
      end
    end

    @inventories = get_selection(search_params)

    session[:filter] = { 'stores' => @checked_stores, 'codes' => @checked_codes }
  end

  def report
    @store   = params[:store] || 0
    @product = params[:code]  || 0

    @inventories = get_selection(params)

    respond_to do |format|
      format.html {}
      format.text { send_data render_to_string('_text_report').encode(:crlf_newline => true),
                              filename: 'Store_%s_PRCode_%02d.txt' % [ @store, @product ] }
    end
  end

  # GET /inventories/1
  # GET /inventories/1.json
  def show
  end

  # GET /inventories/new
  def new
    @inventory = Inventory.new
  end

  # GET /inventories/1/edit
  def edit
  end

  # POST /inventories
  # POST /inventories.json
  def create
    @inventory = Inventory.new(inventory_params)

    respond_to do |format|
      if @inventory.save
        format.html { redirect_to inventories_path, notice: 'Inventory was successfully created.' }
        format.json { render :show, status: :created, location: @inventory }
      else
        format.html { render :new }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # Get /inventories/import
  def bulk
    @inventory = Inventory.new
    @status = InventoryStatus.new
  end

  # POST /inventories/import
  def bulk_import
    @inventory = Inventory.new
    @status = Inventory.bulk_import(params[:inventory][:bulk])

    render :bulk
  end

  # PATCH/PUT /inventories/1
  # PATCH/PUT /inventories/1.json
  def update
    respond_to do |format|
      if @inventory.update(inventory_params)
        format.html { redirect_to inventories_path, notice: 'Inventory was successfully updated.' }
        format.json { render :show, status: :ok, location: @inventory }
      else
        format.html { render :edit }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventories/1
  # DELETE /inventories/1.json
  def destroy
    @inventory.destroy
    respond_to do |format|
      format.html { redirect_to inventories_path, notice: 'Inventory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def clear
    Inventory.all.destroy_all
    session[:filter] = nil
    redirect_to inventories_path, notice: 'All Records have been Cleared!'
  end

  def clear_params(params)
    if params.kind_of?(Hash)
      params.keys.each do |key|
        params.delete(key) if params[key].blank? or ( params[key].kind_of?(Array) and params[key][0].blank? )
      end
    end
    params || {}
  end

  def get_selection(params = {})
    inv = Inventory.all
    myparams = clear_params(params)

    if myparams
      inv = inv.where(store: myparams[:store]) if myparams.has_key?(:store)
      inv = inv.where(code:  myparams[:code] ) if myparams.has_key?(:code)
      inv = inv.where('roll LIKE ?', '%' + myparams[:roll].upcase + '%' ) if myparams.has_key?(:roll)
    end

    inv.order(:store, :code, :created_at)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventory
      @inventory = Inventory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inventory_params
      params.require(:inventory).permit(:bulk, :product, :store, :code, :roll, :width, :feet, :inches)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def show_flash(options = {})
    output = ActiveSupport::SafeBuffer.new

    [:success, :error, :notice, :alert].each do |message|
      output << content_tag(:p, class: ["flash-#{message.to_s}", options[:class]], tabindex: '0') do
        flash[message]
      end if flash[message].present?

      flash[message] = nil
    end

    output
  end

  def admin?
    session[:access] == 'admin'
  end

end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/views/inventories/_bulk_form.haml
= simple_form_for @inventory, url: import_inventories_url do |f|
  - if @status.errors.any?
    #error_explanation
      %h2 #{pluralize(@status.errors.count, 'error')} prohibited this data from being imported:
      %ul
        - @status.errors.each do |message|
          %li= message

  - if @status.valid > 0
    %p#notice #{@status.valid} out of #{pluralize(@status.total, 'record')} were successfully imported.

  .field= f.input :bulk, as: 'text', required: true, focus: true, label: 'Bulk Input - Upload Tricoder data here'
  .actions= f.submit 'Bulk Import'

app/views/inventories/_form.haml
= simple_form_for @inventory do |f|
  - if @inventory.errors.any?
    #error_explanation
      %h2 #{pluralize(@inventory.errors.count, 'error')} prohibited this inventory from being saved:
      %ul
        - @inventory.errors.full_messages.each do |message|
          %li= message

  .field= f.input :store

  .field= f.input :code, label: 'Product Code'
  .field= f.input :roll, label: 'Roll Number'

  .field= f.input :width
  .field= f.input :feet,   label: 'Length (Feet)'
  .field= f.input :inches, label: 'Length (Inches)'

  .actions= f.submit

app/views/inventories/_nav.haml
.search-tools
  = simple_form_for :inventory, url: inventories_path, method: 'get' do |f|
    .filter
      %label Store Codes
      %div
        = f.input :store,
          collection: @stores,
          checked: @checked_stores,
          label: false,
          :as => :check_boxes,
          :item_wrapper_tag => :li,
          :collection_wrapper_tag => :ol,
          :boolean_style => :inline

    .filter
      %label Product Codes
      %div
        = f.input :code,
          collection: @products,
          checked: @checked_codes,
          label: false,
          :as => :check_boxes,
          :item_wrapper_tag => :li,
          :collection_wrapper_tag => :ol,
          :boolean_style => :inline

    .search-bar
      .search-and-submit
        %label Roll Number
        = f.input :roll, placeholder:'Search Roll Number', label: false
        -#%button{type:'submit'}= icon('search')

    .trigger
      %button{type:'submit'} Update

app/views/inventories/_text_report.haml
- @inventories.each do |inventory|
  = "#{inventory.inventory_code('@')}"
  = "#{inventory.width}"
  = "#{inventory.feet}"
  = "#{inventory.inches||0}"
  = ''
zy

app/views/inventories/bulk.haml
%h1 Data Importer

= render 'bulk_form'
%br
= link_to 'Home', inventories_path

app/views/inventories/edit.haml
%h1 Edit Inventory Record

#inventory
  = render 'form'

  .links
    = link_to 'Show', @inventory
    |
    = link_to 'Back', inventories_path

app/views/inventories/index.haml
#inventory
  = render 'nav'

  .button-group
    - if admin?
      .button.clear
        = button_to 'Clear All Records', clear_inventories_path, :method => :delete, class: 'warning',
          data: { confirm: "This will erase ALL DATA\r\nAre you SURE this is what you want?" }
    .button= button_to 'New Record', new_inventory_path, :method => :get
    .button= button_to 'Bulk Import', import_inventories_path, :method => :get

  - if @inventories.empty?
    %h2 No Products
    %p
      Please begin by importing your inventory counts.
      .button= button_to 'Bulk Import', import_inventories_path, :method => :get

  - @inventories.group_by{|r| r.store}.each do |store, inventories|
    - next unless store
    .store
      %h1 Store #{store}
      - inventories.group_by{|r| r.code}.each do |code, groups|
        - next unless code
        .product
          .report= button_to "Export Store #{store}, PR Code #{'%02d'%code}", report_inventories_path(store,code,:text), method: 'get'
          %h2 Product Code #{'%02d' % code}
          %table
            %thead
              %tr
                %th Roll
                %th Width
                %th Length
                %th

            %tbody
              - groups.each do |inventory|
                %tr{ class: ('updated' if inventory.updated?) }
                  %td= link_to inventory.roll, inventory
                  %td= '%02.02f' % inventory.width
                  %td= '%.02f'   % inventory.length
                  %td
                    = link_to icon('edit', 'Edit'), edit_inventory_path(inventory), :method => :get, class: 'blue'
                    - if admin?
                      |
                      = link_to icon('remove', 'Delete'), inventory, :method => :delete, class: 'red', data: { confirm: 'Are you sure?' }

app/views/inventories/new.haml
%h1 New inventory

= render 'form'
= link_to 'Back', inventories_path

app/views/inventories/report.haml
%h1 Inventory report
%h2 Product code #{'%02d' % @product} for Store #{@store}

%p.product-list
  - @inventories.each do |inventory|
    %p
      %strong= inventory.inventory_code(nil)
      \: #{inventory.width} foot wide,
      #{inventory.length} linear feet

%br
  = link_to 'Back', inventories_path
  |
  = link_to 'Text Version', report_inventories_path(@store, @product, :text)

app/views/inventories/show.haml
#inventory
  .container
    .label Roll Number:
    .field= @inventory.roll

    .label Product Code:
    .field= @inventory.code

    .label Width:
    .field= @inventory.width

    .label Length (feet):
    .width= @inventory.feet

    .label Length (inches):
    .field= @inventory.inches

  .links
    = button_to 'Edit', edit_inventory_path(@inventory), :method => :get
    -#= button_to 'Back', inventories_path

app/views/layouts/application.html.haml
!!!
%html
%head
  %title RFMS Inventory Importer
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

.page-container
  = show_flash
  = yield